config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update], path: :u, param: :username do
    resources :recipes, only: [:show], param: :hashid do
      get :saved, on: :collection
    end
  end

  resources :recipes, only: [:index, :new, :create, :edit, :update], param: :hashid, path: '/' do
    get :search, on: :collection
    post :toggle_save
    get :new_local, on: :collection
    get :new_external, on: :collection
  end

  match 'cameras/:slug', as: :camera, to: 'recipes#camera', via: [:post, :get]
  match 'sensors/:slug', as: :sensor, to: 'recipes#sensor', via: [:post, :get]

  get :about, to: 'pages#about', as: :about

  root "recipes#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include Hashid::Rails

  belongs_to :user
  belongs_to :parent, class_name: 'Recipe', optional: true
  belongs_to :sensor, class_name: 'Sensor', optional: true, foreign_key: :sensor_id, counter_cache: true
  has_many :saves, class_name: 'Save', dependent: :destroy

  has_one_attached :poster
  has_one_attached :photo_1
  has_one_attached :photo_2

  enum film_simulation: {
    provia: 0,
    velvia: 1,
    astia: 2,
    classic_chrome: 3,
    pro_neg_hi: 4,
    pro_neg_std: 5,
    classic_neg: 6,
    eterna: 7,
    eterna_bleach_bypass: 8,
    acros: 9,
    monochrome: 10,
    sepia: 11
  }, _prefix: true

  enum dynamic_range: {
    auto: 0,
    '100%': 1,
    '200%': 2,
    '400%': 3
  }, _prefix: true

  enum grain_roughness: {
    off: 0,
    weak: 1,
    strong: 2
  }, _prefix: true

  enum grain_size: {
    small: 0,
    large: 1
  }, _prefix: true

  enum white_balance: {
    auto: 0,
    white_priority: 1,
    ambience_priority: 2,
    color_temperature: 3,
    daylight: 4,
    shade: 5,
    fluorescent_light_1: 6,
    fluorescent_light_2: 7,
    fluorescent_light_3: 8,
    incandescent: 9,
    underwater: 10
  }, _prefix: true

  enum color_chrome_effect: {
    off: 0,
    weak: 1,
    strong: 2
  }, _prefix: true

  enum color_chrome_effect_blue: {
    off: 0,
    weak: 1,
    strong: 2
  }, _prefix: true

  enum :source_type, {
    local: 0,
    external: 1
  }, prefix: true

  validates :name, presence: true
  validates :sensor, presence: true
  validates :poster, attached: true, content_type: :jpg

  validates :color_temperature, presence: true, numericality: true, if: :white_balance_color_temperature?

  with_options if: :source_type_local? do |recipe|
    recipe.validates :film_simulation, presence: true
    recipe.validates :photo_1, content_type: :jpg
    recipe.validates :photo_2, content_type: :jpg
  end

  with_options if: :source_type_external? do |recipe|
    recipe.validates :original_author, presence: true
    recipe.validates :original_url, presence: true, uniqueness: { scope: :source_type }
  end

  def saved_by?(user)
    saves.find_by(user: user).present?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[ create update edit new destroy ]
  before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :set_camera, only: %i[camera]
  before_action :set_sensor, only: %i[sensor]

  # GET /recipes or /recipes.json
  def index
    scope = Recipe.all
                  .order(created_at: :desc)
                  .includes([:sensor, :parent, poster_attachment: :blob, user: { avatar_attachment: :blob }])

    scope = apply_search_query(scope) if params[:q]

    @pagy, @recipes = pagy(scope)
    @saves = find_saves(@recipes)

    if params[:page]
      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end
  end

  def search
    redirect_to root_path and return if params[:q].blank?
    scope = Recipe.all
                  .order(created_at: :desc)
                  .includes([:sensor, :parent, poster_attachment: :blob, user: { avatar_attachment: :blob }])

    scope = apply_search_query(scope) if params[:q]

    @pagy, @recipes = pagy(scope)
    @saves = find_saves(@recipes)

    render :index
  end

  def camera
    @recipes = Recipe.all.order(created_at: :desc).includes([:sensor, :parent, poster_attachment: :blob, user: { avatar_attachment: :blob }])
    @scope = @recipes.joins(:sensor).where('sensors.slug': Sensor.compatibility_matrix[@camera.sensor.slug.to_sym]).order(created_at: :desc)
    @pagy, @recipes = pagy(@scope)
    @saves = find_saves(@recipes)
    render :index
  end

  def sensor
    @recipes = Recipe.all.order(created_at: :desc).includes([:sensor, :parent, poster_attachment: :blob, user: { avatar_attachment: :blob }])
    scope = @recipes.joins(:sensor).where('sensors.slug': Sensor.compatibility_matrix[@sensor.slug.to_sym]).order(created_at: :desc)
    @pagy, @recipes = pagy(scope)
    @saves = find_saves(@recipes)

    render :index
  end

  def saved
    @user = User.find_by!(username: params[:user_username])
    scope = @user.saved_recipes.order('saves.id DESC')
    @pagy, @recipes = pagy(scope)
    @saves = find_saves(@recipes)

    respond_to do |format|
      format.html { render 'users/saved' }
      format.turbo_stream { render :index }
    end
  end

  def toggle_save
    authenticate_user!

    @recipe = Recipe.find(params[:recipe_hashid])
    save = @recipe.saves.find_or_initialize_by(user: current_user)
    save.persisted? ? save.destroy : save.save!

    if params[:card]
      render(
        turbo_stream: turbo_stream.replace(
          helpers.dom_id(@recipe, :card),
          partial: 'recipes/recipe_card',
          locals:  {
            recipe: @recipe,
            saves:  find_saves(@recipe)
          }
        )
      )
    else
      redirect_back fallback_location: [@recipe.user, @recipe]
    end
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    scope = Recipe.where.not(id: @recipe.id).order(created_at: :desc).limit(21).includes([:user, :sensor, :parent, poster_attachment: :blob])
    @pagy, @recipes = pagy_countless(scope)
    @saves = find_saves(@recipes)

    if params[:page]
      respond_to do |format|
        format.html
        format.turbo_stream { render 'recipes/index' }
      end
    end
  end

  # GET /recipes/new
  def new
    authenticate_user!
  end

  # GET /recipes/new_local
  def new_local
    authenticate_user!
    @recipe = Recipe.source_type_local.new

    if params[:fork_of]
      @recipe.parent = Recipe.find(params[:fork_of])

      @recipe.sensor = @recipe.parent.sensor
      @recipe.film_simulation = @recipe.parent.film_simulation
      @recipe.dynamic_range = @recipe.parent.dynamic_range
      @recipe.highlights = @recipe.parent.highlights
      @recipe.shadows = @recipe.parent.shadows
      @recipe.color = @recipe.parent.color
      @recipe.noise_reduction = @recipe.parent.noise_reduction
      @recipe.sharpening = @recipe.parent.sharpening
      @recipe.clarity = @recipe.parent.clarity
      @recipe.grain_roughness = @recipe.parent.grain_roughness
      @recipe.grain_size = @recipe.parent.grain_size
      @recipe.color_chrome_effect = @recipe.parent.color_chrome_effect
      @recipe.color_chrome_effect_blue = @recipe.parent.color_chrome_effect_blue
      @recipe.white_balance = @recipe.parent.white_balance
      @recipe.white_balance_red = @recipe.parent.white_balance_red
      @recipe.white_balance_blue = @recipe.parent.white_balance_blue
    end
  end

  # GET /recipes/new_external
  def new_external
    authenticate_user!
    @recipe = Recipe.source_type_external.new
  end

  # GET /recipes/1/edit
  def edit
    authenticate_user!
  end

  # POST /recipes or /recipes.json
  def create
    authenticate_user!

    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    error_action = @recipe.source_type_local? ? :new_local : :new_external

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to user_recipe_url(@recipe.user, @recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render error_action, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    authenticate_user!
    if @recipe.update(recipe_params)
      redirect_to user_recipe_url(@recipe.user, @recipe), notice: "Recipe was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    # Remove these two methods once google indexed cameras and sensors properly
    def set_camera
      if params[:slug].to_i.to_s == params[:slug]
        redirect_to camera_path(Camera.find(params[:slug]))
      else
        @camera = Camera.find_by!(slug: params[:slug])
      end
    end

    # Remove these two methods once google indexed cameras and sensors properly
    def set_sensor
      if params[:slug].to_i.to_s == params[:slug]
        redirect_to sensor_path(Sensor.find(params[:slug]))
      else
        @sensor = Sensor.find_by!(slug: params[:slug])
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:hashid])
    end

    def apply_search_query(scope)
      scope
        .joins(:user)
        .where('name ILIKE :query OR users.username ILIKE :query', query: "%#{params[:q]}%")
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:film_simulation,
                                     :dynamic_range,
                                     :highlights,
                                     :shadows,
                                     :color,
                                     :noise_reduction,
                                     :sharpening,
                                     :clarity,
                                     :grain_roughness,
                                     :grain_size,
                                     :color_chrome_effect,
                                     :color_chrome_effect_blue,
                                     :white_balance,
                                     :color_temperature,
                                     :white_balance_red,
                                     :white_balance_blue,
                                     :sensor_id,
                                     :original_author,
                                     :original_url,
                                     :poster,
                                     :photo_1,
                                     :photo_2,
                                     :description,
                                     :name,
                                     :source_type,
                                     :parent_id)
    end
end

app/views/recipes/_form_external.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-8">
    <%= bootstrap_form_with(model: recipe) do |form| %>
      <% if recipe.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

          <ul>
            <% recipe.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.hidden_field :source_type, value: form.object.source_type %>

      <div class="row">
        <div class="col-8">
          <%= form.text_field :name, class: 'form-control-lg', help: 'Keep it short and simple' %>
        </div>

        <div class="col">
          <%= form.select :sensor_id, Sensor.all.map { |s| [s.name, s.id] }, {}, class: 'form-select-lg' %>
        </div>
      </div>

      <div>
        <%= form.url_field :original_url, placeholder: 'https://...', class: 'form-control-lg' %>
      </div>

      <div class="row">
        <div class="col">
          <%= form.text_field :original_author, label: 'Original author name' %>
        </div>

        <div class="col">
          <%= form.file_field :poster, direct_upload: true %>
        </div>
      </div>

      <div>
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_load_more_link.html.erb
<% if pagy.next.present? %>
  <% if user_signed_in? || pagy.page < 2 %>
    <div id="next_link" class="text-center mb-5">
      <%= link_to 'Load more', pagy_url_for(pagy, pagy.next), class: 'btn btn-outline-secondary', data: { disable_with: 'Loading...', method: :get, controller: 'auto-click' } %>
    </div>
  <% else %>
    <div class="text-center mt-4 mb-5">
      <p class="text-muted mb-3">Want to see all <%= pluralize(pagy.count, 'recipe') %>?</p>
      <a href="<%= new_user_registration_path %>" class="btn btn-primary">Sign up to continue</a>
      <a href="<%= new_user_session_path %>" class="btn btn-link">or sign in</a>
    </div>
  <% end %>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="row justify-content-center mt-lg-5 mb-lg-3">
    <div class="col-12 col-lg-8">
      <div class="row mb-3 align-items-center justify-content-between">
        <div class="col-6">
          <h1 class="mb-0 h4"><%= recipe.name %></h1>
          <div class="small">
            <% if recipe.original_author.present? %>
              <span class="text-muted"><%= recipe.original_author %> via</span>
            <% end %>

            <%= link_to recipe.user, class: 'text-decoration-none' do %>
              <%= image_tag avatar_url(recipe.user), class: 'rounded-circle', size: '15x15' %>
              <%= recipe.user.display_name || recipe.user.username %>
            <% end %>

            <% if recipe.parent %>
              <div class="text-muted small d-inline">
                &bull; Forked from <%= link_to recipe.parent.name, [recipe.parent.user, recipe.parent], class: 'text-reset' %> by <%= link_to (recipe.parent.user.display_name || recipe.parent.user.username), recipe.parent.user, class: 'text-reset' %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="col-auto text-right d-flex">
          <% if @recipe.saved_by?(current_user) %>
            <%= button_to 'Saved', recipe_toggle_save_path(@recipe), class: 'btn btn-success me-1', method: :post %>
          <% else %>
            <%= button_to 'Save', recipe_toggle_save_path(@recipe), class: "btn btn-outline-secondary me-1 #{'disabled' unless user_signed_in?}", method: :post %>
          <% end %>

          <% if recipe.source_type_local? %>
            <a class="btn btn-outline-secondary" href="<%= new_local_recipes_path(fork_of: @recipe.to_param) %>">Fork</a>
          <% end %>

          <% if current_user == @recipe.user %>
            <a href="<%= edit_recipe_path(@recipe) %>" class="btn btn-outline-secondary ms-1">Edit</a>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% if recipe.source_type_external? %>
    <div class="row justify-content-center mb-5">
      <div class="col-12">
        <div class="card mb-3 text-bg-light">
          <div class="row g-0 align-items-center">
            <div class="col-md-6">
              <%= link_to recipe.original_url, target: :_blank do %>
                <%= image_tag recipe.poster.representation(resize_to_fill: [880, 500]), class: 'img-fluid rounded-start' %>
              <% end %>
            </div>

            <div class="col-md-6">
              <div class="card-body p-md-5">
                <h5 class="card-title">External recipe for <%= recipe.sensor.name %></h5>
                <p class="card-text">Original author of this recipe and photos is <strong><%= recipe.original_author %></strong> and this recipe is hosted outside fujixrecipes.
                Ownership will be transfered to a proper account in cause of him/her opening one. Use the link below to see the original recipe.</p>

                <p class="card-text text-muted small">If you are the author and you don't want this recipe to be here, please reach me at <a href="https://instagram.com/mbajur" class="alert-link" target="_blank">@mbajur</a></p>

                <hr>

                <a href="<%= recipe.original_url %>" class="btn btn-primary" target="_blank">See original recipe ↗</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-12 col-md-8">
        <p>
          <%= image_tag recipe.poster.representation(resize_to_fill: [880, 550]), class: 'img-fluid' %>
        </p>

        <% if recipe.photo_1.attached? %>
          <p>
            <%= image_tag recipe.photo_1.representation(resize_to_fill: [880, 550]), class: 'img-fluid' %>
          </p>
        <% end %>

        <% if recipe.photo_2.attached? %>
          <p>
            <%= image_tag recipe.photo_2.representation(resize_to_fill: [880, 550]), class: 'img-fluid' %>
          </p>
        <% end %>

        <div class="lead">
          <%= simple_format recipe.description %>
        </div>
      </div>

      <div class="col">
        <dl class="row sticky-top pt-3">
          <dt class="col-sm-7">Sensor</dt>
          <dd class="col-sm-5"><%= link_to recipe.sensor&.name, "/?s=#{recipe.sensor&.slug}" %></dd>

          <dt class="col-sm-7">Film simulation</dt>
          <dd class="col-sm-5"><%= recipe.film_simulation %></dd>

          <dt class="col-sm-7">Dynamic range:</dt>
          <dd class="col-sm-5"><%= recipe.dynamic_range %></dd>

          <dt class="col-sm-7">Highlights:</dt>
          <dd class="col-sm-5"><%= recipe.highlights %></dd>

          <dt class="col-sm-7">Shadows:</dt>
          <dd class="col-sm-5"><%= recipe.shadows %></dd>

          <dt class="col-sm-7">Color:</dt>
          <dd class="col-sm-5"><%= recipe.color %></dd>

          <dt class="col-sm-7">Noise reduction:</dt>
          <dd class="col-sm-5"><%= recipe.noise_reduction %></dd>

          <dt class="col-sm-7">Sharpening:</dt>
          <dd class="col-sm-5"><%= recipe.sharpening %></dd>

          <dt class="col-sm-7">Clarity:</dt>
          <dd class="col-sm-5"><%= recipe.clarity %></dd>

          <dt class="col-sm-7">Grain roughness:</dt>
          <dd class="col-sm-5"><%= recipe.grain_roughness %></dd>

          <dt class="col-sm-7">Grain size:</dt>
          <dd class="col-sm-5"><%= recipe.grain_size %></dd>

          <dt class="col-sm-7">Color chrome effect:</dt>
          <dd class="col-sm-5"><%= recipe.color_chrome_effect %></dd>

          <dt class="col-sm-7">Color chrome effect blue:</dt>
          <dd class="col-sm-5"><%= recipe.color_chrome_effect_blue %></dd>

          <dt class="col-sm-7">White balance:</dt>
          <dd class="col-sm-5">
            <%= recipe.white_balance %>
            <% if recipe.white_balance_color_temperature? %>(<%= recipe.color_temperature %>K)<% end %>
          </dd>

          <dt class="col-sm-7">White balance red:</dt>
          <dd class="col-sm-5"><%= recipe.white_balance_red %></dd>

          <dt class="col-sm-7">White balance blue:</dt>
          <dd class="col-sm-5"><%= recipe.white_balance_blue %></dd>
        </dl>
      </div>
    </div>

    <hr class="my-5">
  <% end %>

  <h3 class="h4 text-center mt-5 mb-4">Other recipes</h3>
  <%= render 'recipes/recipes', recipes: @recipes, pagy: @pagy, saves: @saves %>
</div>

app/views/recipes/_recipe_card.html.erb
<div class="col-12 col-md-4" id="<%= dom_id(recipe, :card) %>">
  <div class="card card-recipe mb-4">
    <% link = recipe.source_type_external? ? recipe.original_url : [recipe.user, recipe] %>
    <%= link_to link, target: (:_blank if recipe.source_type_external?) do %>
      <%= image_tag recipe.poster.representation(resize_to_fill: [634, 400]), class: 'card-img-top h-100', size: '634x400' %>
    <% end %>

    <div class="card-img-overlay bg-gradient" style="height:3rem;">
      <h5 class="card-title mb-1 h6 text-white text-truncate">
        <%= link_to [recipe.user, recipe], class: 'text-reset text-decoration-none' do %>
          <%= recipe.name %>
        <% end %>
      </h5>
    </div>

    <div class="card-body">
      <% if recipe.sensor %>
        <div style="margin-top: -55px; margin-bottom: 30px">
          <a class="badge text-bg-dark text-decoration-none" href="<%= sensor_path(recipe.sensor) %>"><%= recipe.sensor.name %></a>
          <% if recipe.source_type_external? %>
            <abbr href="" class="badge text-bg-light text-decoration-none opacity-50" title="External recipe, hosted on another website">E↗</abbr>
          <% end %>
        </div>
      <% end %>

      <h5 class="card-title mb-1 h6 d-none">
        <%= link_to [recipe.user, recipe], class: 'text-reset text-decoration-none' do %>
          <%= recipe.name %><% if recipe.source_type_external? %> <small class="text-muted" title="External recipe" data-bs-toggle="tooltip" data-bs-placement="right">↗</small><% end %>
        <% end %>
      </h5>

      <div class="card-text text-muted small d-flex">
        <div>
          <%= link_to recipe.user, class: 'text-reset text-decoration-none' do %>
            <%= image_tag avatar_url(recipe.user), class: 'rounded-circle', size: '15x15' %>
            <%= recipe.user.display_name || recipe.user.username %>
          <% end %>

          <% if recipe.parent %>
            <div class="d-inline opacity-50">
              &bull; Forked from <%= link_to recipe.parent.name, [recipe.parent.user, recipe.parent], class: 'text-reset' %> by <%= link_to (recipe.parent.user.display_name || recipe.parent.user.username), recipe.parent.user, class: 'text-reset' %>
            </div>
          <% end %>
        </div>

        <div class="ms-auto">
          <% btn_style = "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem; margin-top: -0.6rem; margin-right: -0.3rem; margin-bottom: -0.6rem;" %>

          <% if recipe.saves_count.positive? %>
            <span class="d-inline-block btn btn-link disabled text-decoration-none" style="<%= btn_style %>" title="Recipe saved <%= pluralize(recipe.saves_count, 'time') %>">
              <%= recipe.saves_count %>
            </span>
          <% end %>

          <% if user_signed_in? %>
            <% if saves.include?(recipe.id) %>
              <%= button_to 'Saved', recipe_toggle_save_path(recipe, card: true), form_class: 'd-inline-block', class: "btn btn-success btn-sm", style: btn_style, method: :post %>
            <% else %>
              <%= button_to 'Save', recipe_toggle_save_path(recipe, card: true), form_class: 'd-inline-block', class: "btn btn-outline-secondary btn-sm #{'disabled' unless user_signed_in?}", style: btn_style, method: :post %>
            <% end %>
          <% else %>
            <a href="<%= new_user_session_path %>" class="btn btn-outline-secondary btn-sm" style="<%= btn_style %>" title="Sign-in to save this recipe">Save</a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_recipes.html.erb
<% set_meta_tags robots: 'noindex' if pagy.page > 1 %>

<div class="row" id="recipes">
  <%= render 'recipes/recipes_grid', recipes: recipes, saves: saves, pagy: @pagy %>
</div>

<% if pagy.next.present? && (local_assigns[:load_more_link] != false) %>
  <%= render 'recipes/load_more_link', pagy: @pagy %>
<% end %>

<% if recipes.none? %>
  <p class="lead text-center">No recipes to show</p>
<% end %>

app/views/recipes/_recipes_grid.html.erb
<%= render collection: recipes, partial: 'recipes/recipe_card', as: :recipe, locals: { saves: saves, pagy: pagy } %>

app/views/recipes/edit.html.erb
<h1 class="h2 text-center mb-4 mt-4">Editing recipe</h1>

<% partial = @recipe.source_type_external? ? 'form_external' : 'form_local' %>
<%= render partial, recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", [@recipe.user, @recipe] %>
</div>

app/views/recipes/index.html.erb
<% set_meta_tags canonical: root_url %>

<%= content_for :hero do %>
  <div class="bg-dark py-4 mb-4 text-light">
    <div class="container">
      <div class="text-center">
        <p class="lead">
          <% if params[:q] %>
            Showing <%= pluralize(@pagy.count, 'recipe')%> for 	&bdquo;<%= params[:q] %>&rdquo;
            <% set_meta_tags title: "Fujifilm recipes for „#{params[:q]}”", canonical: search_recipes_path(q: params[:q]) %>
          <% elsif @camera %>
            Showing <%= pluralize(@pagy.count, 'recipe')%> for <strong>Fujifilm <%= @camera.name %></strong>
            <% set_meta_tags title: "Fujifilm #{@camera.name}", description: "Recipes for Fujifilm #{@camera.name}", canonical: camera_url(@camera) %>
          <% elsif @sensor %>
            Showing <%= pluralize(@pagy.count, 'recipe')%> compatible with <strong>Fujifilm <%= @sensor.name %></strong> sensor
            <% set_meta_tags title: "Fujifilm #{@sensor.name}", description: "Recipes for Fujifilm #{@sensor.name} sensor", canonical: sensor_url(@sensor) %>
          <% else %>
            Welcome to Fuji X Recipes! Use the buttons below to filter our database:
          <% end %>
        </p>

        <div class="btn-group">
          <div class="dropdown">
            <a href="#" class="btn dropdown-toggle <%= @camera ? 'btn-secondary' : 'btn-outline-secondary' %>" data-bs-toggle="dropdown">Camera <% if @camera %>: <strong><%= @camera.name %></strong><% end %></a>
            <ul class="dropdown-menu">
              <% Camera.all.order(name: :desc).each do |camera| %>
                <li>
                  <a class="dropdown-item d-flex justify-content-between <%= 'active' if @camera == camera %>" href="<%= camera_path(camera) %>">
                    <div class="ms-2 me-auto">
                      <%= camera.name %>
                    </div>

                    <div>
                      <span class="badge bg-secondary rounded-pill opacity-50" title="<%= pluralize camera.recipes_count, 'recipe' %>"><%= camera.recipes_count %></span>
                    </div>
                  </a>
                </li>
              <% end %>
            </ul>
          </div>

          <div class="dropdown ms-2">
            <a href="#" class="btn dropdown-toggle <%= @sensor ? 'btn-secondary' : 'btn-outline-secondary' %>" data-bs-toggle="dropdown">Sensor <% if @sensor %>: <strong><%= @sensor.name %></strong><% end %></a>
            <ul class="dropdown-menu">
              <% Sensor.all.each do |sensor| %>
                <li>
                  <a class="dropdown-item d-flex justify-content-between <%= 'active' if @sensor == sensor %>" href="<%= sensor_path(sensor) %>">
                    <div class="ms-2 me-auto">
                      <%= sensor.name %>
                    </div>

                    <div>
                      <span class="badge bg-secondary rounded-pill opacity-50" title="<%= pluralize sensor.recipes_count, 'recipe' %>"><%= sensor.recipes_count %></span>
                    </div>
                  </a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'recipes/recipes', recipes: @recipes, pagy: @pagy, saves: @saves %>

app/views/recipes/index.turbo_stream.erb
<%= turbo_stream.append 'recipes' do %>
  <%= render 'recipes/recipes_grid', recipes: @recipes, saves: @saves, pagy: @pagy %>
<% end %>

<%= turbo_stream.update "next_link" do %>
  <%= render 'recipes/load_more_link', pagy: @pagy %>
<% end %>

app/views/recipes/new.html.erb
<h1 class="h2 text-center mb-4 mt-4">New recipe</h1>

<div class="row justify-content-center">
  <div class="col-12 col-md-8">
    <div class="card-group">
      <div class="card text-center">
        <div class="card-body p-5">
          <p class="card-text lead">I created my own recipe and i want to share it on fujixrecipes</p>
          <a href="<%= new_local_recipes_path %>" class="btn btn-primary">Add mine</a>
        </div>
      </div>
      <div class="card text-center">
        <div class="card-body p-5">
          <p class="card-text lead">I want to share the link to a recipe that already exists on another website</p>
          <a href="<%= new_external_recipes_path %>" class="btn btn-primary">Link external</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/new_external.html.erb
<h1 class="h2 mb-4 text-center mt-4">New recipe link</h1>

<%= render "form_external", recipe: @recipe %>

app/views/recipes/new_local.html.erb
<h1 class="h2 mb-4 text-center mt-4">New recipe</h1>

<%= render "form_local", recipe: @recipe %>