config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update], path: :u, param: :username do
    resources :recipes, only: [:show], param: :hashid do
      get :saved, on: :collection
    end
  end

  resources :recipes, only: [:index, :new, :create, :edit, :update], param: :hashid, path: '/' do
    get :search, on: :collection
    post :toggle_save
    get :new_local, on: :collection
    get :new_external, on: :collection
  end

  match 'cameras/:slug', as: :camera, to: 'recipes#camera', via: [:post, :get]
  match 'sensors/:slug', as: :sensor, to: 'recipes#sensor', via: [:post, :get]

  get :about, to: 'pages#about', as: :about

  root "recipes#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_one_attached :avatar

  has_many :recipes
  has_many :saves, class_name: 'Save'
  has_many :saved_recipes, through: :saves, source: :recipe

  validates :avatar, content_type: /\Aimage\/.*\z/
  validates :username, presence: true, uniqueness: true
  validates :username, format: { with: /\A[a-z0-9_]+\z/i }, length: { maximum: 30 }
  validates :display_name, length: { maximum: 30 }
  validates :bio, length: { maximum: 500 }

  def to_param
    username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(username: params[:username])
    scope = @user.recipes.order(created_at: :desc).includes([:sensor, :parent, poster_attachment: :blob, user: { avatar_attachment: :blob }])
    @pagy, @recipes = pagy(scope)
    @saves = find_saves(@recipes)

    if params[:page]
      respond_to do |format|
        format.html
        format.turbo_stream { render 'recipes/index' }
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :display_name, :avatar, :bio, :website)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user, width = 30, height = 30)
    if user.avatar.attached?
      user.avatar.representation(resize_to_fill: [width, height])
    else
      hash = Digest::MD5.hexdigest(user.email)
      "https://www.gravatar.com/avatar/#{hash}?s=#{width}&d=mp"
    end
  end
end

app/views/users/_profile_layout.html.erb
<div class="row py-5 align-items-center">
  <div class="col-4 text-center">
    <%= image_tag avatar_url(@user, 200, 200), class: 'rounded-circle w-100 h-auto', size: '150x150', style: 'max-width:150px' %>
  </div>

  <div class="col">
    <div class="d-flex">
      <h1 class="h3 mb-3">
        <%= @user.username %>
      </h1>

      <% if @user == current_user %>
        <div class="align-self-center ms-3">
          <a href="<%= edit_user_path(@user) %>" class="btn btn-sm btn-outline-secondary">Edit profile</a>
        </div>
      <% end %>
    </div>

    <div>
      <% if @user.display_name %><strong><%= @user.display_name %></strong><% end %>
      <%= simple_format @user.bio %>

      <% if @user.website %>
        <%= link_to @user.website.gsub('http://', '').gsub('https://', ''), @user.website, rel: 'me nofollow noopener noreferrer', target: '_blank' %>
      <% end %>
    </div>
  </div>
</div>

<ul class="nav nav-tabs justify-content-center mb-4">
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:action] == 'show' %>" aria-current="page" href="<%= user_path(@user) %>">Recipes created by <%= @user.username %></a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'active' if params[:action] == 'saved' %>" href="<%= saved_user_recipes_path(@user) %>">Saved</a>
  </li>
</ul>

<%= yield %>

app/views/users/edit.html.erb
<%= bootstrap_form_for(@user) do |f| %>
  <%= f.text_field :username %>
  <%= f.text_field :display_name %>
  <%= f.file_field :avatar %>
  <%= f.text_area :bio %>
  <%= f.url_field :website %>
  <%= f.submit %>
<% end %>

app/views/users/saved.html.erb
<% set_meta_tags canonical: saved_user_recipes_url(@user) %>

<%= render layout: 'users/profile_layout' do %>
  <%= render 'recipes/recipes', recipes: @recipes, pagy: @pagy, saves: @saves %>
<% end %>

app/views/users/show.html.erb
<% set_meta_tags title: @user.username, description: "Recipes posted by #{@user.username}", canonical: user_url(@user) %>

<%= render layout: 'users/profile_layout' do %>
  <%= render 'recipes/recipes', recipes: @recipes, pagy: @pagy, saves: @saves %>
<% end %>