config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update], path: :u, param: :username do
    resources :recipes, only: [:show], param: :hashid do
      get :saved, on: :collection
    end
  end

  resources :recipes, only: [:index, :new, :create, :edit, :update], param: :hashid, path: '/' do
    get :search, on: :collection
    post :toggle_save
    get :new_local, on: :collection
    get :new_external, on: :collection
  end

  match 'cameras/:slug', as: :camera, to: 'recipes#camera', via: [:post, :get]
  match 'sensors/:slug', as: :sensor, to: 'recipes#sensor', via: [:post, :get]

  get :about, to: 'pages#about', as: :about

  root "recipes#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if ENV['GA_ID'] %>
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV.fetch('GA_ID') %>"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        document.addEventListener('turbo:load', function(event) {
          gtag('config', '<%= ENV.fetch('GA_ID') %>', {
            page_location: event.detail.url
          });
        })
      </script>
    <% end %>

    <%= display_meta_tags(default_meta_tags) %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link type="application/opensearchdescription+xml" rel="search" href="/omnisearch.xml"/>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/feather-icons"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container">
        <a class="navbar-brand h1 mb-0" href="/">Fuji X Recipes</a>

        <form class="ms-3 d-none d-md-flex" role="search" action="<%= search_recipes_path %>">
          <input class="form-control me-2" type="search" placeholder="Search..." aria-label="Search" name="q" value="<%= params[:q] %>">
        </form>

        <ul class="navbar-nav d-none d-lg-flex">
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
        </ul>

        <div>
          <div class="d-inline-block d-md-none">
            <a href="<%= new_recipe_path %>" class="btn btn-outline-success"><i data-feather="plus"></i></a>

            <% if user_signed_in? %>
              <a href="<%= saved_user_recipes_path(current_user) %>" class="btn btn-outline-secondary"><i data-feather="bookmark"></i></a>
            <% end %>
          </div>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="me-auto mb-2 mb-lg-0"></div>
          <a class="btn btn-outline-success btn-sm d-none d-md-inline-block me-3" href="<%= new_recipe_path %>">+ Add recipe</a>

          <ul class="navbar-nav">
            <form class="d-flex d-md-none" role="search" action="<%= search_recipes_path %>">
              <input class="form-control me-2" type="search" placeholder="Search..." aria-label="Search" name="q" value="<%= params[:q] %>">
            </form>

            <li class="nav-item d-inline-block d-md-none"><%= link_to 'About', about_path, class: 'nav-link' %></li>

            <% if user_signed_in? %>
              <li class="nav-item d-none d-md-inline-block"><a href="<%= saved_user_recipes_path(current_user) %>" class="nav-link">Saved recipes</a></li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                  <%= image_tag avatar_url(current_user, 25, 25), class: 'rounded-circle', size: '25x25' %>
                  <%= current_user.username %>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li><a class="dropdown-item" href="<%= user_path(current_user) %>">Your profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <%= button_to 'Sign-out', destroy_user_session_path, class: 'dropdown-item', method: :delete, data: { turbo: false } %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign-in', new_user_session_path, class: 'nav-link', data: { turbo: false } %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield :hero %>

    <div class="container">
      <% if notice %>
        <div class="toast-container position-fixed bottom-0 end-0 p-3">
          <div id="liveToast" class="toast fade show text-bg-info" style="--bs-bg-opacity: .8;" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
            <div class="d-flex">
              <div class="toast-body">
                <%= notice %>
              </div>

              <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <script>
      feather.replace()
    </script>
  </body>
</html>